### ISSUE TITLE
automate installation on macOS

### ISSUE THREAD

**Issue by sota1235** [sota1235/dotfiles#74]
# TODO

- [ ] Dock app list
- [ ] caps lock to control key
- [ ] left click with 2 fingers
- [ ] click by tapping
- [ ] trackpad speed
- [ ] scroll direction
- [ ] pinch with 2 fingers
- [ ] key repeat speed
